

name: Deploy to Productioon

on:
  push:
    branches: main
jobs:
  
  
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Development
        if: github.ref == 'refs/heads/main'
        env:
          PRIVATE_KEY: ${{ secrets.NEW_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.NEW_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{secrets.NEW_HOSTNAME}} '
            cd /var/www/html/mcehassan &&
            sudo git pull origin main '
            

      
  
